// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package params

// The `record` plugin's OWN CUE schema — the typed plugin_input for the
// `record` session-recording check verb. It is the SINGLE SOURCE for this
// plugin's params, used two ways (the same contract core `spec` and the http
// plugin use):
//
//  1. GENERATE the Go param struct — `cue exp gengotypes` (driven by the cue:gen
//     pipeline, which wraps this with `package params` + `@go(params)`) emits
//     ../params/cue_types_gen.go, so the provider decodes plugin_input into a
//     TYPED struct, never a hand-parsed map.
//  2. VALIDATE authored input AT RUNTIME — the plugin serves this source over the
//     Describe channel; the host splices it onto the base (base ++ plugin) and
//     validates every authored `record:` step's plugin_input against
//     #RecordInput.
//
// Since the schema-compaction cutover the per-verb fields LEFT core #Op: an
// authored `record: <method>` step (scalar sugar) or `record: {method: …,
// record_name: …}` (map form) desugars to the INTERNAL plugin/plugin_input
// envelope, and every record-exclusive modifier lives HERE — the former core
// #RecordMethod enum is this def's `method` field. The shared assertion
// matchers (exit_status/stdout/stderr) and the general `timeout` stay on core
// #Op, read off the step Op by the provider.
//
// SELF-CONTAINED: it references NO base def, so it compiles standalone
// (gengotypes + the load-gate compile) AND splices onto the base (base ++ plugin
// is a def-name collision check, not a base-reference resolver).
type RecordInput struct {
	// method — the record method to dispatch (the former core #RecordMethod
	// enum; also the scalar-sugar primary: `record: <method>`).
	Method string `yaml:"method,omitempty" json:"method"`

	// record_name — the recording session name (default "default").
	RecordName string `yaml:"record_name,omitempty" json:"record_name,omitempty"`

	// record_mode — terminal (asciinema) / desktop (pixelflux-record or
	// wf-recorder); empty means auto-detect from the venue's tools.
	RecordMode string `yaml:"record_mode,omitempty" json:"record_mode,omitempty"`

	// record_fps — the desktop-recorder frame rate (default 30).
	RecordFps int `yaml:"record_fps,omitempty" json:"record_fps,omitempty"`

	// record_audio — capture audio with the desktop recording.
	RecordAudio bool `yaml:"record_audio,omitempty" json:"record_audio,omitempty"`

	// record_env — extra environment for the recorder process (desktop mode needs the
	// compositor session on VM/desktop venues: record_env: {XDG_RUNTIME_DIR: /run/user/1000,
	// WAYLAND_DISPLAY: wayland-1}; container defaults are /tmp + wayland-0). Every stated
	// key overrides the default; extra keys pass through. Values are static strings.
	RecordEnv map[string]string `yaml:"record_env,omitempty" json:"record_env,omitempty"`

	// text — the command line `cmd`/`run` sends into the recording's tmux session.
	Text string `yaml:"text,omitempty" json:"text,omitempty"`

	// settle_ms — how long `run` waits after sending the text before returning
	// (default 1500). The command's output becomes part of the recording.
	SettleMs int `yaml:"settle_ms,omitempty" json:"settle_ms,omitempty"`

	// artifact — the host path `stop` copies the recording to, and `gif`
	// copies the rendered .gif to.
	Artifact string `yaml:"artifact,omitempty" json:"artifact,omitempty"`

	// artifact_min_bytes / artifact_min_cast_events — the post-run
	// artifact-reality assertions (sdk.RunArtifactValidators).
	ArtifactMinBytes int `yaml:"artifact_min_bytes,omitempty" json:"artifact_min_bytes,omitempty"`

	ArtifactMinCastEvents int `yaml:"artifact_min_cast_events,omitempty" json:"artifact_min_cast_events,omitempty"`

	// --- gif method (agg) — render a stopped terminal recording to an animated GIF ---
	// theme — agg color theme (asciinema, dracula, monokai, github-dark,
	// solarized-dark, ...); empty uses the recording's embedded theme when present.
	Theme string `yaml:"theme,omitempty" json:"theme,omitempty"`

	// font_size — agg font size in px (default 16).
	FontSize int `yaml:"font_size,omitempty" json:"font_size,omitempty"`

	// speed — agg playback speed multiplier (default 1; >1 speeds up, <1 slows down).
	Speed float64 `yaml:"speed,omitempty" json:"speed,omitempty"`

	// idle_time_limit — agg cap on any single inactive period, in seconds
	// (default 5), so long pauses don't bloat the GIF.
	IdleTimeLimit int `yaml:"idle_time_limit,omitempty" json:"idle_time_limit,omitempty"`

	// fps_cap — agg maximum GIF frame rate (default 30); lower values produce
	// smaller files at the cost of motion smoothness.
	FpsCap int `yaml:"fps_cap,omitempty" json:"fps_cap,omitempty"`

	// select — agg frame selection (e.g. "5..30", "50%", "marker:build..marker:test",
	// "12.5"); renders only part of the recording or discrete terminal states.
	Select string `yaml:"select,omitempty" json:"select,omitempty"`

	// cols / rows — agg terminal size override (re-render at a different geometry).
	Cols int `yaml:"cols,omitempty" json:"cols,omitempty"`

	Rows int `yaml:"rows,omitempty" json:"rows,omitempty"`

	// no_loop — agg plays the GIF once instead of looping forever.
	NoLoop bool `yaml:"no_loop,omitempty" json:"no_loop,omitempty"`

	// last_frame_duration — agg holds the final frame for this many seconds
	// (default 3) before the GIF loops or ends.
	LastFrameDuration int `yaml:"last_frame_duration,omitempty" json:"last_frame_duration,omitempty"`

	// renderer — agg rendering backend: "swash" (default) or "resvg".
	Renderer string `yaml:"renderer,omitempty" json:"renderer,omitempty"`

	// --- session method (Cutover A instrument model — venue-side session; the
	// tmux transport IS the session, already invocation-surviving) ---
	// action — the session lifecycle action (start/stop/status); empty means start
	// (the default lifecycle action, mirroring the instrument phase bracket).
	Action string `yaml:"action,omitempty" json:"action,omitempty"`

	// session_id — the venue-scoped session identity. When set it BECOMES the
	// record_name (tmux session names must not collide across venues); falls back
	// to record_name when empty.
	SessionId string `yaml:"session_id,omitempty" json:"session_id,omitempty"`

	// state_dir — the run's state directory; stop writes the instrument evidence
	// row (<state_dir>/row.json) here.
	StateDir string `yaml:"state_dir,omitempty" json:"state_dir,omitempty"`

	// venue — the venue the session runs on (evidence-row provenance).
	Venue string `yaml:"venue,omitempty" json:"venue,omitempty"`

	// phase — the instrument phase bracket (evidence-row provenance).
	Phase string `yaml:"phase,omitempty" json:"phase,omitempty"`
}
